public class QuestionFormat
{
    public static Dictionary<int, Dictionary<int, int>> questionFormat = new Dictionary<int, Dictionary<int, int>>{

        {
            1, new Dictionary<int, int>{
                {
                    1,1
                }
            }
        },
        {
            2, new Dictionary<int, int>{
                {
                    1,20
                }
            }
        },
        {
            3, new Dictionary<int, int>{
                {
                    1,4
                }
            }
        },
        {
            4, new Dictionary<int, int>{}
        },
        {
            5, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,12
                },
                {
                    3,12
                },
                {
                    4,12
                },
                {
                    5,12
                }
            }
        },
        {
            6, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,12
                },
                {
                    3,12
                }
            }
        },
        {
            7, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,12
                },
                {
                    3,12
                },
                {
                    4,12
                },
                {
                    5,12
                },
                {
                    6,12
                }
            }
        },
        {
            8, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,12
                },
                {
                    3,12
                },
                {
                    4,12
                },
                {
                    5,12
                },
                {
                    6,12
                },
                {
                    7,12
                },
                {
                    8,12
                },
                {
                    9,12
                },
                {
                    10,12
                }
            }
        },
        {
            9, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,12
                },
                {
                    3,12
                },
                {
                    4,12
                },
                {
                    5,12
                },
                {
                    6,12
                }
            }
        },
        {
            10, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,12
                },
            }
        },
        {
            11, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,1
                },
                {
                    3,1
                },
                {
                    4,1
                },
                {
                    5,1
                },
                {
                    6,1
                },
                {
                    7,1
                }
            }
        },
        {
            12, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,4
                },
                {
                    3,4
                },
            }
        },
        {
            13, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,1
                },
                {
                    3,1
                },
                {
                    4,1
                },
                {
                    5,1
                },
                {
                    6,1
                },
                {
                    7,1
                },
                {
                    8,1
                }
            }
        },
        {
            14, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,5
                },
                {
                    3,5
                },
                {
                    4,5
                }
            }
        },
        {
            15, new Dictionary<int, int>{
                {
                    1,1
                },
                {
                    2,1
                },
                {
                    3,1
                },
                {
                    4,1
                },
                {
                    5,1
                },
                {
                    6,1
                },
                {
                    7,1
                },
                {
                    8,1
                },
                {
                    9,1
                },
                {
                    10,1
                },
                {
                    11,1
                },
                {
                    12,1
                },
                {
                    13,1
                },
                {
                    14,1
                },
                {
                    15,1
                },
                {
                    16,1
                },
                {
                    17,1
                },
                {
                    18,1
                }
            }
        },

     };
}